### ISSUE TITLE
sync builds option

### ISSUE THREAD

**Issue by uBlock-user** [macchrome/winchrome#1]
Thanks for compiling Windows builds, however would you do SYNC builds too ?

**Comment by uBlock-user** [comment]
@macchrome you there ?

**Comment by macchrome** [comment]
I only compile windows Chromium builds once in a while; but will compile a sync build the next time that I do. 

Nik at chromium.woolyss.com compiles Chromium sync builds on a regular basis.

**Comment by uBlock-user** [comment]
Yes, I'm aware. I am only asking to know if you're willing compile a sync build too. Thanks.
