### ISSUE TITLE
flag "win-10-tab-search-caption-button" missing since v114

### ISSUE THREAD

**Issue by achtchaern** [macchrome/winchrome#101]
Hi there,

The tab search UI can no longer be disabled. The flag does not exist anymore. In version 113.0.5672.127, it was still there. 

Can it be re-added? I'd like to hide this button.

**Comment by macchrome** [comment]
I'm not interested in obsolete parameters.

The tab search UI functionality is located in  chrome/browser/ui/ui_features.cc

BASE_FEATURE(kTabSearchChevronIcon,
             "TabSearchChevronIcon",
             base::FEATURE_ENABLED_BY_DEFAULT);

In the next build, I will set the default to disabled.

**Comment by achtchaern** [comment]
Thank you! Maybe consider editing the release notes as the flag is mentioned there.
