### ISSUE TITLE
jitsi, webrtc, wasm

### ISSUE THREAD

**Issue by vimjim** [macchrome/winchrome#104]
I'm using & promoting woolyss and your "ungoogled-chromium/winchrome" as portable solution for years to use with Jitsi Meet for online education - until 114.0.5735.94.
After that release webrtc (iphandling) default setting changed, making Jitsi meetings impossible. The "reg" fix is only applicable for "admins".
With 114.0.5735.134 wasm is blocked, disabling "background blur etc" in Jitsi.
Google Chrome (portable) is working fine :-/ but not my favorite ;-)
I really would appreciate if your ungoogled-chromium/winchrome webrtc/wasm functions could be enabled by some command line options or by master_preferences file to provide a solution for students & colleagues.
Thanks in advance !

**Comment by macchrome** [comment]
Javascript JIT (wasm): chrome://settings/content/javascript-jit
Webgl: chrome://settings/content/webgl

CLI parameters: http://peter.sh/experiments/chromium-command-line-switches/

Eg. --disable-webgl --js-flags="--jitless" 

I've explained my approach to webrtc: The IP handling policy of WebRTC https://github.com/macchrome/winchrome/releases/tag/v114.5735.110-M114.0.5735.110-r1135570-Win64


chrome://settings/content/javascript-jit and chrome://settings/content/webgl will be removed in v115

**Comment by ltguillaume** [comment]
> chrome://settings/content/javascript-jit and chrome://settings/content/webgl will be removed in v115

Is this an upstream decision?

**Comment by vimjim** [comment]
> Javascript JIT (wasm): chrome://settings/content/javascript-jit Webgl: chrome://settings/content/webgl
> 
> CLI parameters: http://peter.sh/experiments/chromium-command-line-switches/
> 
> Eg. --disable-webgl --js-flags="--jitless"
> 
> I've explained my approach to webrtc: The IP handling policy of WebRTC https://github.com/macchrome/winchrome/releases/tag/v114.5735.110-M114.0.5735.110-r1135570-Win64
> 
> chrome://settings/content/javascript-jit and chrome://settings/content/webgl will be removed in v115

Thanks for the information, fixed it for the moment ;-)

**Comment by vimjim** [comment]
> Javascript JIT (wasm): chrome://settings/content/javascript-jit Webgl: chrome://settings/content/webgl
> 
> CLI parameters: http://peter.sh/experiments/chromium-command-line-switches/
> 
> Eg. --disable-webgl --js-flags="--jitless"
> 
> I've explained my approach to webrtc: The IP handling policy of WebRTC https://github.com/macchrome/winchrome/releases/tag/v114.5735.110-M114.0.5735.110-r1135570-Win64
> 
> chrome://settings/content/javascript-jit and chrome://settings/content/webgl will be removed in v115

Thanks for the information, fixed it for me ;-)

**Comment by macchrome** [comment]
@ltguillaume 

The switches in question are not part of standard chrome/chromium; they were incorporated from Uazo's bromite build.

**Comment by ltguillaume** [comment]
> @ltguillaume
> 
> The switches in question are not part of standard chrome/chromium; they were incorporated from Uazo's bromite build.

Ah yes, that makes sense. Well, I have to say I find them very useful for some streaming sites that require both. Without them, and considering the new defaults since v114.0.5735.134, I won't be able to use them anymore (and one of them is used on a ~daily basis).

Could you explain why they'll be removed in v115?

**Comment by Meridiano** [comment]
Will we be able to toggle `chrome://settings/content/javascript-jit` and `chrome://settings/content/webgl` on in 115?
I mean there will be no that options but maybe other options.
`regex101.com` requires 1st and `sketchfab.com` requires 2nd.

**Comment by macchrome** [comment]
If chrome://settings/content/javascript-jit and chrome://settings/content/webgl are removed in v115, then unless disabled at the CLI, they default to enabled. The toggle switches enable per site control.

Why they'll be (possibly) removed in v115? 

For an easy life. I have to manually integrate Uazo's patches, (Actually, that is not true - Uazo has automated the process!)  We shall see.

**Comment by ltguillaume** [comment]
> (Actually, that is not true - Uazo as automated the process!) We shall see.

Sounds promising then 🤞

Thanks for explaining!

**Comment by graphixillusion** [comment]
Actually i've found that if i just enable Javascript JIT in a specific site while the main flag is set to off (chrome://settings/content/javascript-jit), the allowed site to run JIT doesn't actually use it properly. You can easily reproduce this on virustotal when you upload some >10MB file: without JIT the checksum calculation is super slow. uazo's Cromite works correctly on this so i think it's some sort of bug in here.

**Comment by ltguillaume** [comment]
Same here: if I disable by default (standard setting) and add an exception to allow either WebGL or JIT on a specific domain, I still get a message in the browser console from the site in question that WebGL/JIT is disabled (I made sure they're _not_ disabled via the command line). Only enabling by default gets WebGL/JIT working.

**Comment by graphixillusion** [comment]
Little update: with the just released 116 version the option to enable/disable JIT is gone and now the browser seems to works good. Always tested with virustotal and hashing.

**Comment by ltguillaume** [comment]
Ah damn, too bad.

**Comment by graphixillusion** [comment]
last update restore previous behaviour. @macchrome is it possible to fix this?
