### ISSUE TITLE
works much slower

### ISSUE THREAD

**Issue by dfa56** [macchrome/winchrome#106]
on tests https://browserbench.org/ ungoogled-chromium-115.0.5790.93-1_Win64.7z works much slower than ungoogled-chromium-114.0.5735.110-1_Win64.7z. And it started with ungoogled-chromium-114.0.5735.134-1_Win64.7z.
With builds from Hibbiki and official Chrome, on versions 114.xxx, there are no slowdowns.

**Comment by mp3sova** [comment]
I confirm!
Also noticeable on Kraken JavaScript Benchmark (kraken-1.1 test)

**Comment by achtchaern** [comment]
A few things to check:

- chrome://settings/content/javascript-jit: Should be "Allow JIT and WebAssembly on a specific site"
- chrome://settings/content/webgl: Should be "Enabled"
- chrome://policy: Disable the policy that prevents Network Prediction (or similar)

**Comment by dfa56** [comment]
We unpack 114.0.5735.110-1_Win64.7z, do not change anything, and immediately run speedtest on https://browserbench.org/ - the result is 190.
We unpack 114.0.5735.134-1_Win64.7z and the next, do not change anything, and immediately run speedtest on https://browserbench.org/ - the result is 110.

**Comment by achtchaern** [comment]
Please read the suggestions above.

**Comment by dfa56** [comment]
achtchaern, do you think that when unpacking 114.0.5735.134-1_Win64.7z, something has changed?!
Google Chrome 114.0.5735.199 gives 190 without any dancing!

**Comment by dfa56** [comment]
thanks achtchaern! It works! I did not know about the new settings items :)

**Comment by dfa56** [comment]
thanks achtchaern! It works! I did not know about the new settings items :)
