### ISSUE TITLE
HEVC

### ISSUE THREAD

**Issue by trimechee** [macchrome/winchrome#108]
Thank you very much for giving us this wonderful browser!

I have a question please, I noticed this mention:

Disable Hardware HEVC CLI flag: --disable-features=PlatformHEVCDecoderSupport

therefore, the 2 versions of our beloved Winchrome :

ungoogled-chromium-115.0.5790.131-1_windows.7z (64-bit)

and

115.0.5790.131_ungoogled_mini_installer.exe (64-bit)

havee HEVC disabled?

 and if so, why please?

**Comment by achtchaern** [comment]
I think they're enabled in both the archive- and the installer-based builds. The mentioned line in the release notes shows how to disable it for those users who don't want it. If you want to test it yourself:

https://web.archive.org/web/20230319103654/http://h265.webmfiles.org/embed-h265-video.php

**Comment by trimechee** [comment]
Awesome, very interesting ! Thank you so much @achtchaern 💯 🥇 

i have question please, why some users would like to disable hevc ? hevc may be bad ?

**Comment by trimechee** [comment]
@achtchaern , I'm really surprised very surprised, I tested the link you sent me with firefox browser

https://web.archive.org/web/20230319103654/http://h265.webmfiles.org/embed-h265-video.php


 and firefox can't play hevc videos !! I'm surprised that a big famous company like firefox didn't get license for hevc codec?!! is there a way to add hevc to firefox please ?

**Comment by trimechee** [comment]
@arm64-v9a Interesting ! Thank you so much :)
