### ISSUE TITLE
chrome://settings/content/fontAccess missing since June 2023

### ISSUE THREAD

**Issue by Rexadev** [macchrome/winchrome#111]

**Comment by macchrome** [comment]
Ask the chromium Authors!

**Comment by Rexadev** [comment]
> Ask the chromium Authors!

How does Ungoogled Chromium works ?

1. Is it first chromium is patched and everyone builds their own way with - complier cpu optimizations, codecs, google sync API ?
2. So [macchrome/winchrome](https://github.com/macchrome/winchrome)'s and all other "Ungoogle Chromium" is downstream from [ungoogled-software/ungoogled-chromium](https://github.com/ungoogled-software/ungoogled-chromium).
3. Do [ungoogled-software/ungoogled-chromium](https://github.com/ungoogled-software/ungoogled-chromium) repo run https://chromium.woolyss.com/ ?
4. Is Bromite, Chromite downstream for [ungoogled-software/ungoogled-chromium](https://github.com/ungoogled-software/ungoogled-chromium) repo too ? 
5. What other projects downstream from here ?
6. Where does https://github.com/Eloston fit in ungoogled-chromium

**Comment by Rexadev** [comment]
> Ask the chromium Authors!

Can you backport

**Comment by Rexadev** [comment]
> Ask the chromium Authors!

Renamed to chrome://settings/content/localFonts

@macchrome
