### ISSUE TITLE
chrome://settings/content/javascript-jit: Rephrase, acts Weird

### ISSUE THREAD

**Issue by Rexadev** [macchrome/winchrome#114]
### Description

1. Upstream will not fix it https://github.com/ungoogled-software/ungoogled-chromium/issues/2485

2. Rephrase settings in chrome://settings/content/javascript-jit

3. In my backup win 11 computer  `Block JIT and WebAssembly on a specific Website` means `Allow all except listed`  but in my main win 11 computer is **acts as `Block all Except`**

4. In my backup win 11 **computer exception list (either allow or block) is flipped** (Block these websites turn into Allow... and other way around) when switching between `Block JIT and WebAssembly on a specific Website` and `Allow`

### Problem

Options on `chrome://settings/content/javascript-jit` are `Allow/Block JIT and WebAssembly on a specific Website.`
It is confusing. `Block JIT and WebAssembly on a specific Website` means `Allow all except listed` and vice-versa. 

### Possible solutions

1. I would suggest to rename `Block JIT and WebAssembly on a specific Website.` to `Allow JIT and WebAssembly` and when using it 
use this list for exception -

`Block sites from using just-in-time compilation, using only interpreted JavaScript; less performant but more secure against security vulnerabilities.`

in this section -

```
Customized behaviors

Sites listed below follow a custom setting instead of the default
```

2. Also -  Grey-out `Allow List` (`Allow sites to use just-in-time compilation; more performant but a constant source of security vulnerabilities.`) when `Block JIT and WebAssembly on a specific Website.` option is selected

### Build I am using

Marmaduke Windows x64 Portable https://github.com/macchrome/winchrome

**Comment by macchrome** [comment]
Possible solutions:

1. Default behaviour: the wording "on a specific site." is superflous.

2. I'm not willing to consider this reduction in functionality.

**Comment by Rexadev** [comment]
> In my backup win 11 computer exception list (either allow or block) is flipped (Block these websites turn into Allow... and other way around) when switching between Block JIT and WebAssembly on a specific Website and Allow

@macchrome

**Comment by macchrome** [comment]
That is not my problem!

**Comment by Rexadev** [comment]
> That is not my problem!

ungoogled-software/ungoogled-chromium ? but they are not accepting saying if you use macchrome tell him

@macchrome
