### ISSUE TITLE
Kick.com not working with Releases above "113"

### ISSUE THREAD

**Issue by vveed** [macchrome/winchrome#116]
Hello Sir,

I dont get a Player to watch a stream on kick.com with Release 117-114, all Releases above 113.0 have this Problem.

Iam using now 113.0.5672.127 and it works Fine.

can you please take a look at this Problem, maybe other site have also a problem with this kind of Player?

Thank you

**Comment by macchrome** [comment]
https://kick.com/yuppy

javascript-jit
webgl

**Comment by vveed** [comment]
Hello Sir, 
thank you for your answere, but i dont know what that means, iam sorry :(

javascript-jit
webgl

have i to disabled or enabled it? Where can i find this Option, i lookt at the Chrome Flags but cant find it.

Sorry
