### ISSUE TITLE
web.whatsapp JavaScript JIT

### ISSUE THREAD

**Issue by selvios** [macchrome/winchrome#119]
Hi.
The web.whatsapp added to exceptions (https://file.coffee/u/FSfndq4HtG4xJU1wSZ6jU.png) is not working on chrome://settings/content/javascript-jit page, specifically the QR code is not loading. Only enabling Allow JIT and WebAssembly on a specific site. for all sites helps.

**Comment by macchrome** [comment]
Try adding the site associated with the QR code to the javascript-jit exception list.

This is a well know issue with:  WebGL, WebRTC and javascript-jit: https://github.com/uazo/cromite/issues/268

**Comment by Rusenche** [comment]
>@macchrome: Try adding the site associated with the QR code to the javascript-jit exception list.
> 
> This is a well know issue with: WebGL, WebRTC and javascript-jit: [uazo/cromite#268](https://github.com/uazo/cromite/issues/268)

For those wondering what to do: Add here: `chrome://settings/content/javascript-jit` - among exceptions this: `[*.]whatsapp.com`

![assss](https://github.com/macchrome/winchrome/assets/18578128/5b2d7c2b-eb3e-4b53-bbaa-670c9595f834)
