### ISSUE TITLE
Make "energy saver" option to permanently available even when plugged in without battery

### ISSUE THREAD

**Issue by trimechee** [macchrome/winchrome#121]
Hello, thank you so much for the new aweome updated version ! 🥇  

We have request please : sadly "energy saver" feature doesn't work when plugged in, our notebook is not very powerful and and doest't have a big memory ram and we can use many heavy program at thesame time and battery can get tired...it will be great to add option to enable permanently energy saver even when plugged in (without battery) to avoid freeze and lag, thank you so much !

https://support.google.com/chrome/answer/12929150?visit_id=638227751357191071-2548025678&p=chrome_memory_saver&rd=1#memory_saver&zippy=%2Cturn-memory-saver-on-or-off%2Cturn-energy-saver-on-or-off

So our hope please is make the "energy saver" option permanently available even when plugged in without battery, thank you :)

**Comment by macchrome** [comment]
I've nothing to add to the issue that your raised at: https://github.com/ungoogled-software/ungoogled-chromium/issues/2569

**Comment by trimechee** [comment]
Hello, you invented a browser independent and different from ungoogled chromium, and we do not know if ungoogled chromium will implement this option, and I use your browser and I do not use ungooled chromium, when I talked about this option in the ungooogld chromium page, it's so you don't get tired by letting the ungoogled chromium team do the work, and a manager told me you don't use ungoogld chromium because I use your browser and he told me they are not going to examine your request because i am not using ungoogled chromium....so I had to lie and open a new issue and make them believe that I am using ungoogled chromium, but Eleston the main developer of ungoogld chromium hasn't responded to me so I'm not sure my request will be considered, and the Marmaduke web browser has its own specificities that's why i made thise requestion ..... anyway I'm going to make Microsoft Edge Browser my main web browser because it has this feature even plugged in,and librewolf seems to have nativly energy saver ..... it's regrettable chromium is losing market share
