### ISSUE TITLE
Random behaviour when clicking or double clicking the tab bar

### ISSUE THREAD

**Issue by Poonsta** [macchrome/winchrome#124]
Version 119.0.6045.110 (Official Build, ungoogled-chromium) (64-bit)
Win 10

Sometimes when clicking the tab bar (outside of tabs) the entire content of the open tab gets selected (similar to Ctrl-A). When double clicking the tab bar (outside of tabs) to maximize the window, a random link from the open tab gets opened in a new tab instead of maximizing the window.
The behavior is quite random, does not always happen, but happens often enough to get annoying.

The best way I found to reproduce it (though it is not the only way it happens, and it is not guaranteed to always work):

1. Open a Chromium window, not maximized. Position it on the screen so that there is enough room on the right side of it for the Bookmarks panel, but not much more room.
2. Open a web page in the current tab. Move the page down a bit, but not all the way to the bottom.
3. Click on a part of the open page that is not a link or an entry field or anything like that, so basically the page gets the focus (even though nothing noticable happens.
4. Open the browser menu (click the three dots button on the top right corner). Move the mouse down to Bookmarks, the Bookmarks panel opens to the right of the browser. Move the mouse on a bookmarks folder, the contents pop up to the left, inside the browser window area. (Tried to get a picture of it but I could not, the open menu just kept closing when I tried. Sorry.)
5. Without clicking on any bookmark, or touching any other thing in the open menu (that is making sure the bookmark panel inside the browser window area stays open) move the mouse to the tab bar and click or double click on the tab bar. When clicking the page contents get selected. When double clicking a random link from the open tab gets open in a new tab instead of the window maximizing, but this is even less predictable than the page selection.

**Comment by macchrome** [comment]
I'll take your word for it!
