### ISSUE TITLE
web.whatsapp / web.telegram

### ISSUE THREAD

**Issue by selvios** [macchrome/winchrome#127]
Neither QR code nor phone number binding is saved after closing the browser. The sites have been [added](https://file.coffee/u/BGiGFEsXRRzFCt1DV-VQj.png) to the exclusions. What could be the reason?

**Comment by macchrome** [comment]
https://github.com/macchrome/winchrome/issues/119

follow the leads and also search uazo's site. How you configure the browser is up to you.
