### ISSUE TITLE
Please add autoupdate function.

### ISSUE THREAD

**Issue by rickastley8** [macchrome/winchrome#128]
I love this browser and I would have supported you if I had money. I want a auto update function in the app that downloads the latest ungoogled-chromium version. 
![image](https://github.com/macchrome/winchrome/assets/105724585/f348da4e-bbea-4228-845e-7aa3263799d2)
I also found out that your app dosen't have the icons in the context menu like normal chrome or chromium does. I also found your website tells (C) 2022 ungoogled-chromium Authors instead of 2023. When 2023 is going to end. Wait for 2024 to change it! I am not doing bad things by putting (C) 2022... in this post. The copyright is to you not to me and I like this app and want this issue resolved in the near feature.

**Comment by rickastley8** [comment]
![image](https://github.com/macchrome/winchrome/assets/105724585/330444e5-2573-47c4-b8d7-2246fadfd16d)

I use ExplorerPatcher to make windows 11 look like windows 10.

**Comment by macchrome** [comment]
ok

**Comment by rickastley8** [comment]
> ok

What? Are you adding the function. I would really like to with the ability to disable updates.

**Comment by rickastley8** [comment]
> That's a feature we can't add unfortunately.:-(

**Comment by rickastley8** [comment]
Cool @ltguillaume but I want the dev to actually implement this and this could make this browser more popular and I might ditch firefox for the better chromium browser engine than the slow firefox one.

**Comment by rickastley8** [comment]
Okay will your app add auto update function. I don't really care about it only being by the dev itself. But thank you so much @ltguillaumeI like your comments and like someone doing something that I want.

**Comment by rickastley8** [comment]
I got an email in Mozilla Thunderbird that this post is closed and I checked it to be true but wouldn't that mean the post will no longer show up and is considered solved? I can't understand this but thank you so much @ltguillaume for commenting! Really your comments were useful and I was happy that somebody commented here!

**Comment by rickastley8** [comment]
Sorry for the rickroll name this profile very old back 2 years ago in early 2022 when I discovered rick roll. Will update profile soon! @rickastley8 is going away.

**Comment by mrfoxesite** [comment]
Thank you so much sir @ltguillaume Huge respect to your application program.

**Comment by mrfoxesite** [comment]
Okay sir as you say, Mr.Guillaume. I shall delete this discussion for you sir.

**Comment by mrfoxesite** [comment]
How do I delete this discussion #128?

**Comment by mrfoxesite** [comment]
Sir, it does not work- 
![image](https://github.com/macchrome/winchrome/assets/105724585/f74e4de9-e584-4e54-9269-0229212f94dd)

**Comment by mrfoxesite** [comment]
I put the path to ungoogled chromium sir (%localappdata%\Chromium\Application\chrome.exe)
Contents of ini file: [Settings]
Path=C:\Users\Anonymous\AppData\Local\Chromium\Application\chrome.exe
[Log]
LastResult=Could not determine the build type of Thorium.
LastRun=08:51 Friday, 19 January 2024   
 and 
[thorium-winupdater-main.zip](https://github.com/macchrome/winchrome/files/13983831/thorium-winupdater-main.zip)
[Thorium-WinUpdater_1.8.1.zip](https://github.com/macchrome/winchrome/files/13983832/Thorium-WinUpdater_1.8.1.zip)
The first file did not work bat file crashed.

**Comment by MINORITYmaN** [comment]
>  I want a auto update function in the app that downloads the latest ungoogled-chromium version.

https://github.com/henrypp/chrlauncher
uses winchrome and works like charm.

![image](https://github.com/macchrome/winchrome/assets/2734697/66f98e3b-2fb6-4e11-a0f5-dd9e0e903636)
![image](https://github.com/macchrome/winchrome/assets/2734697/30826ed6-fc6a-4ba7-ae2f-2d3ec5990172)
![image](https://github.com/macchrome/winchrome/assets/2734697/7ec57ea5-0c29-4203-801b-fed74f24472b)
