### ISSUE TITLE
No video on Zoom (Can't detect WebGL?) (114+)

### ISSUE THREAD

**Issue by opusforlife2** [macchrome/winchrome#129]
Zoom was working fine on this browser for me when using version 109 on Windows 7. But on 119 on Windows 10, there is no video, only black screens for people and screen shares. However, using RobRich's AVX build version 121 from Woolyss works fine.

I've investigated this on my own and hit a dead end. Here's what I've found so far:

- For some reason, even though WebGL is enabled in settings, the browser console shows this error message when opening a Zoom meeting landing page:
> Could not get context for WebGL version 2

- There are a bunch of other follow up errors like WebGL initialisation failing, being unable to create a canvas, etc.
- The WebGL and WebGL 2 test pages on get.webgl.org work fine.

Is this a bug? Or do you think something is wrong with my settings?

**Comment by patrickbergner** [comment]
WebGL is disabled by default. You need to enable it.

Settings -> Search for webgl -> Website Settings -> Bottom of the page -> Additional Content Settings -> WebGL -> Enabled

**Comment by opusforlife2** [comment]
> even though WebGL is enabled in settings

^

**Comment by dfa56** [comment]
Starting from version 114, the following settings appeared:
	chrome://settings/content/javascript-jit
	chrome://settings/content/webgl
	chrome://settings/content/webrtc
By default they are turned off!

**Comment by opusforlife2** [comment]
All turned on manually. Bug occurs despite that.

**Comment by dfa56** [comment]
Does version 109 work on Windows 10?

**Comment by opusforlife2** [comment]
Yup. No such error. But there are no toggles for WebRTC, WebGL, or JIT, either. I don't know if that pollutes the test.

**Comment by dfa56** [comment]
The switches appeared in version 114, you can check it on it

**Comment by opusforlife2** [comment]
Ah, yes. Bug exists on 114.

**Comment by dfa56** [comment]
Does version 113 work?

**Comment by opusforlife2** [comment]
(╯°□°）╯︵ ┻━┻

I'll check...

**Comment by opusforlife2** [comment]
Nope. 113 is fine.

**Comment by dfa56** [comment]
Maybe it’s worth looking at some other flags?

**Comment by opusforlife2** [comment]
I've tried everything I could think of personally. Fiddled with settings, extensions, extension settings, and flags.

**Comment by dfa56** [comment]
So the flag
#disable-webgl - Disabled
And
chrome://settings/content/webgl - Enabled

**Comment by opusforlife2** [comment]
Yep.

**Comment by dfa56** [comment]
Version 120 has appeared, maybe it will work?

**Comment by opusforlife2** [comment]
Already tried.

**Comment by dfa56** [comment]
It looks like it started with ungoogled-chromium-114.0.5735.134-1, and before ungoogled-chromium-114.0.5735.110-1 it worked fine.

**Comment by opusforlife2** [comment]
Oh, nice catch. I didn't think to test the older build from the same release tag.

**Comment by macchrome** [comment]
Stale topic

**Comment by opusforlife2** [comment]
@macchrome The bug still exists.

Edit: Do you need more logs or something?

**Comment by opusforlife2** [comment]
@macchrome Are you unable to find the buggy code? @dfa56 helped pinpoint the exact 2 versions between which it was introduced.

**Comment by opusforlife2** [comment]
@macchrome Ping.
