### ISSUE TITLE
How to add incognito button in context menu?

### ISSUE THREAD

**Issue by Jadovran** [macchrome/winchrome#133]
How to add incognito button in context menu?
![image](https://github.com/macchrome/winchrome/assets/24756032/f60d3e27-e2e7-4076-9177-7a669aaf66cd)
Pls help

**Comment by macchrome** [comment]
Pin an active Chromium session to the task bar.

This is not an issue: I'm not a help desk!

**Comment by Jadovran** [comment]
Already, and it's not worked.
