### ISSUE TITLE
Session data is not saved in v122.0.6261.56

### ISSUE THREAD

**Issue by graphixillusion** [macchrome/winchrome#135]
Hi there. As the title says, with the last version (122.0.6261.56) the session data is not saved when you close and reopen the program. So if you login into something, close and reopen chromium, the session cookie is erased so you need to login again. ungoogled-chromium-122.0.6261.56-2 is affected too by this problem. ungoogled-chromium-121.0.6167.185-1 doesn't have this problem and works good.

**Comment by dfa56** [comment]
Hi, chrome://settings/content/siteData

**Comment by macchrome** [comment]
As suggested: chrome://settings/content/siteData

https://github.com/ungoogled-software/ungoogled-chromium/pull/2681

https://github.com/ungoogled-software/ungoogled-chromium/pulls?q=cookie

https://github.com/ungoogled-software/ungoogled-chromium/issues?q=cookie

**Comment by graphixillusion** [comment]
I think i have understood what's going on: the problem seems to be a wrong flag passed to the executables which doesn't work anymore with 122. The flag is --disable-encryption. With 122 i need to use --disable-encryption-win and with it it does work as expected.

**Comment by macchrome** [comment]
OK, well spotted.

**Comment by ltguillaume** [comment]
> > The flag is --disable-encryption. With 122 i need to use --disable-encryption-win and with it it does work as expected.
> 
> How did you find this new flag? No information found on Google...

@graphixillusion Plus, it's simply not true as far as I can tell: `--disable-encryption` still works, while with `--disable-encryption-win` all (session) data and settings are lost.

**Comment by graphixillusion** [comment]
@ltguillaume i don't know what's going on but i have the same results as @E021ntox: --disable-encryption-win works fine in 122. --disable-encryption doesn't work anymore. This is just happened in the last 122 build: 121 works fine with the --disable-encryption flag

**Comment by ltguillaume** [comment]
The existence of a `--disable-encryption-win` switch seems to have been debunked in https://github.com/ungoogled-software/ungoogled-chromium/pull/591#issuecomment-2050443590 unless it is specific to @macchrome's build: 
> Well, passing `--disable-encryption-win` to chromium is the same as passing nothing. It's just an invalid argument. `disable-encryption-win` doesn't even exist in either UG or winchrome. ![image](https://private-user-images.githubusercontent.com/7867461/321773088-5684ee51-31bc-4337-83f8-abf83d10ff74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NjY4NjUsIm5iZiI6MTcxMjg2NjU2NSwicGF0aCI6Ii83ODY3NDYxLzMyMTc3MzA4OC01Njg0ZWU1MS0zMWJjLTQzMzctODNmOC1hYmY4M2QxMGZmNzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTFUMjAxNjA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzUyMmY2YmQ1OTBmY2M5N2MyNmEyMzlkZTU3ZGEwMzM1YzQyNjRkNWFhMmM3NWM1MWEzYTc5NTVlNWUxN2JlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._eBTVDhgMBvk_zGkjguu5Qwe8O0LuT-9vzy1YTr8MsE)

**Comment by graphixillusion** [comment]
@ltguillaume you are right, after your post i did some tests and actually --disable-encryption-win is equal to passing nothing but --disable-encryption still didn't work on my portable installation. So i tried again fresh (deleting the profile folders) and now it seems to works again. I still don't understand the reason and/or why this happens.

**Comment by ltguillaume** [comment]
I just saw this patch that is related to the same issue: https://github.com/Alex313031/thorium/commit/1ac0e00cbca58628e4e24c779dddd65569c158b8
