### ISSUE TITLE
Updating the contents of the `patches/core` directory

### ISSUE THREAD

**Issue by Ricky-Tigg** [macchrome/winchrome#137]
Hello. Like many looking to get a web browser for 64-bit Windows built from Google's **Chromium code** that supports auto-update, among many other browsers in this family, I installed Cromite; Bromite, browser of which Cromite is a fork, is no longer maintained. The site of the repository for Cromite (on this platform) links to https://github.com/henrypp/chrlauncher/releases to achieve this goal. On the latter, the **README.md** file reveals that Cromite is not one of the supported derivatives, but this product is, among the unofficial so'called ungoogled versions of Chromium. Then I thought it might be worth trying, and who knows with a view to permanent adoption.

However, in this repository, I noticed that the
- `patches/core` directory contents were last updated in October 2020. 
- _MS Visual Studio_ version is _2020_.

[Speculations]

You may be considering updating them. If so, this would result in
- to replace Bromite accordingly, thus with Cromite, which is maintained, and would provide its patches (`cromite/build/patches`).
- update to at least version 2022, otherwise 2024 of MS Visual Studio.

**Comment by ltguillaume** [comment]
@Ricky-Tigg For automatic updates, this might suffice: https://codeberg.org/ltguillaume/chromium-winupdater (or https://github.com/ltguillaume/chromium-winupdater)

**Comment by macchrome** [comment]
1. I've no interest in auto-update: I manually check for releases by consulting the Chrome release blog.

2. Occasionally, I build Cromite for macOS for my personal use and curiosity. My Chromium Android build, as stated in the release notes, is derived from Uazo's Cromite; it's unbranded to retain compatibility with my pre Bromite/Cromite builds.

3. Windows builds are cross-compiled, the MS Visual Studio version used is of no consequence:  the apposite SDK packaged to the Chromium Authors' specification is used.

4. All my builds state the source from which they are derived: the essence of any build may be replicated by consulting the original source(s).

**Comment by Ricky-Tigg** [comment]
I have not had to regret having had the curiosity to take an interest in your projects. It's also due to the fact that it awakens so many questions in me, still unanswered. Before even continuing above I must let you know that I am hardly versed in the internal workings of this platform. So you should not be surprised that I am perplexed when I observe things that I may partially understand if not at all.

[_Itguillaume_]
- _Web browser auto-updating_; this functionality, if it did not exist, we would have to invent it.
- On https://codeberg.org/ltguillaume/chromium-winupdater
```html
<li>Chromium WinUpdater currently defaults to <a href="https://github.com/macchrome/winchrome/releases" rel="nofollow">Ungoogled Chromium</a> releases by <a href="https://github.com/macchrome" rel="nofollow">Marmaduke</a>, but supports other variants like <a href="https://github.com/uazo/cromite/releases" rel="nofollow">Cromite by uazo</a>. (...)</li>
```
This seems to need corrections since in the sentence it expresses, the link for _Marmaduke_ refers to https://github.com/macchrome, which itself refers to _macchrome_, not  _Marmaduke_. Also it appears that by _Ungoogled Chromium_, it is referred to a variant of **a particular author**, (otherwise there are many of them), the one of _macchrome_.

[_macchrome_]

Under https://github.com/macchrome/winchrome/releases, on the occasion of each new release we find grouped under _Assets_ releases dating back a few days (models: _122.0.6261.129_ungoogled_mini_installer.exe_, _ungoogled-chromium-122.0.6261.129-1_Win64.7z_) and these _Source code (zip)_, _Source code (tar.gz)_, dating from Oct, 2020. But then, should the fact that they are grouped together be interpreted as meaning that recent productions are built from code not maintained since Oct, 2020? It would seem contrary to common sense to me if that were so.

There are sources of confusion related to the version of MS Visual Studio that is implemented. Which version mention is sometimes _2017_, _2020_ or yet _2022_.

- In https://github.com/macchrome/winchrome
   - `<p class="f4 mb-3 ">Chromium for 64-bit Windows - All Codecs: MS Visual Studio 2017</p>`
   - `<p dir="auto">Chromium for 64-bit Windows - All Codecs: MS Visual Studio 2020</p>`
- In https://github.com/macchrome/winchrome/releases/tag/v122.6261.129-M122.0.6261.129-r1250580-Win64
`<li>SDK 10.0.22621.755 (Visual Studio 2022 17.4.5)</li>`

_2022_ being the highest number among these cited, shouldn't it be the only one to be mentioned as the version of the said product?

Finally, the meaning of the presence of "_GNU/Linux cross-compiled [Ubuntu 22.04.4 LTS (GNU/Linux 6.7.6 x86_64)]_" among the components of the _Chromium v122.0.6261.129-r1250580_ release, which is for 64-bit Windows escapes me. Is it a component, or is it an unusual way of informing, for example that this is the host on which _122.0.6261.129_ungoogled_mini_installer.exe_ and _ungoogled-chromium-122.0. 6261.129-1_Win64.7z_ were compiled?

**Comment by macchrome** [comment]
I've nothing further to add,

**Comment by ltguillaume** [comment]
> [_Itguillaume_]
> This seems to need corrections since in the sentence it expresses, the link for _Marmaduke_ refers to https://github.com/macchrome, which itself refers to _macchrome_, not _Marmaduke_.

AFAIK, Marmaduke == @macchrome (see https://chromium.woolyss.com)

> Also it appears that by _Ungoogled Chromium_, it is referred to a variant of **a particular author**, (otherwise there are many of them), the one of _macchrome_.

No idea what you're trying to say. Ungoogled Chromium is built by different people using different presets, two of them are included, next to Cromite, so the choice is up to you. That's all there is to it.

**Comment by Ricky-Tigg** [comment]
@ltguillaume | Forget these _Marmaduke_ and _macchrome_; in any case it has only an insignificant value in the overall context. And then console yourself like this; _there are those who don't understand, and those who do_. It will always be like this and I can't change anything about it.

@macchrome | [_Closed_] and even as [_completed_]; given what there is to learn there, it cannot be otherwise than well. Interesting project, certainly, but as it appears, -better late than never- not for the reason I thought it was. Another person who doesn't know that _you can't succeed in this environment with the only language, that of code_ - and even then, supposedly.
