### ISSUE TITLE
Distill Web Monitor extension

### ISSUE THREAD

**Issue by mp3sova** [macchrome/winchrome#138]
On your assembly starting from version 118, this extension does not work:
https://chromewebstore.google.com/detail/distill-web-monitor/inlikjemeeknofckkjolnjbpehgadgge?hl=en

Error in the log:
Uncaught TypeError: Cannot read properties of undefined (reading 'SimpleStore')
    at new StoreProxy (service.a7267ed2.js:2045:38)
    at new ServiceProxy (service.a7267ed2.js:2131:18)
    at service.a7267ed2.js:2175:18
StoreProxy	@	service.a7267ed2.js:2045
ServiceProxy	@	service.a7267ed2.js:2131
(anonymous)	@	service.a7267ed2.js:2175

**Comment by macchrome** [comment]
Set  chrome://flags/#web-sql-access to **Enabled**
