### ISSUE TITLE
problem online cameras v119.0<

### ISSUE THREAD

**Issue by mp3sova** [macchrome/winchrome#139]
Thanks for your help with Distill Web Monitor, everything is fine now!
I still have a problem with the online cameras on the site:
https://1tulatv.ru/139583-kamery-tuly-onlayn.html
https://i.imgur.com/vYNxpys.jpeg
On your new builds, the broadcast has stopped working. Maybe we need to enable something additional now?

**Comment by mp3sova** [comment]
Looks like the root of the problem is here:
https://github.com/macchrome/winchrome/issues/118
I checked the builds from v122
https://github.com/ungoogled-software/ungoogled-chromium-windows/releases
No problem

**Comment by macchrome** [comment]
It's a codec demux issue - which I might not fix if it entails losing necessary functionality.

Try this: https://github.com/macchrome/winchrome/releases/download/v61.0.3144.0-r482964-Win64/ungoogled-chromium-123.0.6312.75-2_Win64.7z

SHA1:  F9029D9BF56A6C10E41529A36989BFAB2E2C18A6

**Comment by mp3sova** [comment]
Thanks! It works great :)!

**Comment by macchrome** [comment]
Full loss of no functionality fix -

https://github.com/macchrome/winchrome/releases/download/v61.0.3144.0-r482964-Win64/ungoogled-chromium-123.0.6312.75-3_Win64.7z

SHA1:  89E629443D88EB3DC5C65B753CBCA21FE5FFE80A

**Comment by mp3sova** [comment]
Thank you, this version works with video too. Didn't notice any regressions in the last build as. I only checked the launch of online video due to busyness, today I will run build 75-3 on a working machine :)
