### ISSUE TITLE
Roaming Profile crashes Chromium at startup (v119 and above)

### ISSUE THREAD

**Issue by BrianMwit** [macchrome/winchrome#141]
Chromium ungoogled crash at startup if `RoamingProfileSupportEnabled` is enabled and a roaming profile already exist.
https://chromeenterprise.google/policies/?policy=RoamingProfileSupportEnabled
This policy used to work fine upto v118. It started crashing from v119 onward.

Steps to reproduce
1. Set registry `HKEY_CURRENT_USER` or `HKEY_LOCAL_MACHINE` `\SOFTWARE\Policies\Chromium\RoamingProfileSupportEnabled` to `1`
2. Download release v119 onward: https://github.com/macchrome/winchrome/releases/tag/v119.6045.110-M119.0.6045.110-r1204232-Win64 in .7z format
3. Run `chrome.exe` once, it will work fine and create a Roaming profile at `%APPDATA%\Chromium\User Data\Default\profile.pb`
   - This can be checked at `chrome://sync-internals/` `About` tab > `Local State` > `Local Backend Path`
4. Exit and restart `chrome.exe` again, it will crash at startup
5. Change the registry back to `0`, and `chrome.exe` will start again

I was unaware of this setting. When updating the version, chromium no longer start and I did not know why.

**Comment by macchrome** [comment]
I don't grant administrative (privileged) policies to ungoogled-chromium: I cannot and am not willing to check this issue,

**Comment by BrianMwit** [comment]
I can reproduce the issue by setting the policy at user level (`HKEY_CURRENT_USER`). No administrative (privileged) permission required.
If you meant ungoogle-chromium do not have access to read policy settings, it should ignore the registry value rather than crashing.

The same issue does not occur on `ungoogled-chromium-windows`' build: https://github.com/ungoogled-software/ungoogled-chromium-windows/releases/tag/123.0.6312.105-1.1
