### ISSUE TITLE
Add new patch of Cromite browser to make possible to enable energy battery saver feature even when plugged in 

### ISSUE THREAD

**Issue by feraritn** [macchrome/winchrome#143]
Hello, It seems that Cromite Browser in the last update has achieved the sensational extraordinary great feat of making the "energy battery saver" option active by default even when plugged in even without battery on a desktop computer in order to preserve our battery and energy and the ecology and avoid fan noisy and expensive electricity bill.... We hope Winchrome browser will be able to implement this option even when plugged in because this battery saver option is disabled when plugged in Winchrome browser, thank you so much .

 build/patches/WIN-enable-HighEfficiencyMode-by-default.patch

 https://github.com/uazo/cromite/commit/0dc5d37 https://source.chromium.org/chromium/chromium/src/+/main:chrome/browser/performance_manager/user_tuning/battery_saver_mode_manager.cc https://chromium-review.googlesource.com/c/chromium/src/+/5046375 https://issues.chromium.org/issues/40158973 https://bugs.chromium.org/p/chromium/issues/detail?id=1153154&no_tracker_redirect=1

**Comment by macchrome** [comment]
No. Windows has adequate  user adjustable desktop power saving modes.

**Comment by feraritn** [comment]
Yes we understand ! 

The only problem chromium arbitrarily prevents windows os from applying energy saving measures for computers without battery, you can have an old computer without battery with a memory of only 2Gb, you are plugged in so chromium deactivates the option saving energy while our wish is not to activate this option by default but to give us the possibility of activating it if necessary as Microsoft allows us to do so, for example we open Microsoft Office, pdf reader , web browsers with many extensions....this option can help with an old computer which has limited ram old cpu which lags by deactivating smooth scrolling frame limit...
