### ISSUE TITLE
old interface!

### ISSUE THREAD

**Issue by dfa56** [macchrome/winchrome#144]
Please bring back the old interface! If possible.

**Comment by macchrome** [comment]
https://github.com/macchrome/winchrome/issues/140

Add to the CLI:  --disable-features=CustomizeChromeSidePanel

**Comment by dfa56** [comment]
THANK YOU!!!

**Comment by dfa56** [comment]
Hello,
--disable-features=CustomizeChromeSidePanel does not work in 126.0.6478.103-1_Win64.7z (64-bit).
Please bring back the old interface! If possible.
