### ISSUE TITLE
WebGLRenderingContext unsupported

### ISSUE THREAD

**Issue by atomicdanger** [macchrome/winchrome#150]
chrome://flags > "Override software rendering list" flag is Enabled.
chrome://settings/system > "Use hardware acceleration when available" option is On.
chrome://gpu > WebGL: Hardware accelerated / WebGL2: Hardware accelerated.
chrome://settings/content/webgl and chrome://settings/content/webrtc are enabled

__https://abrahamjuliot.github.io/creepjs/__
**Worker:**
gpu: unsupported
**WebGL:**
Images: blocked
Pixels: blocked
params (0): blocked
exts (0): blocked
gpu: blocked
![Screenshot 2024-08-07 194516](https://github.com/user-attachments/assets/a09d0717-45b0-4458-8f21-619e3ec05c6a)

Tried versions from 127 to 113 but none work.
How can I enable WebGLRenderingContext/WebGL2RenderingContext?

**Comment by macchrome** [comment]
The "Live Radar" on weatherbug.com requires WebGL: it works correctlty.

https://abrahamjuliot.github.io/creepjs/ detects browser fingerprints. The webgl toggle fucntion is derived from Uazo's work and functions as Uazo designed: webgl is not fingerprinted.

Use another browser if the functionality which you require is not supported by this browser.
