### ISSUE TITLE
unable to change the default site fonts on latest portable version of ungoogled-chromium

### ISSUE THREAD

**Issue by kayodde** [macchrome/winchrome#152]
Self explanatory title, i want to change the fonts to japanese noto cjk fonts to prevent chinese fonts from showing but the fonts do not change and are reset after a refresh of the settings page.

I'm using your ungoogled-chromium 128.0.6613.132 build with chrlauncher from https://chromium.woolyss.com/ on Windows 10 iot ltsc 2021 (21h2 19044.4780)

Steps to reproduce:
1. Open up ungoogled-chromium
2. go to settings > appearance > customise fonts
3. change fonts
4. refresh or restart the browser
5. Font settings revert

**Comment by Andarwinux** [comment]
This should be fixed with some extensions, such as Advanced Font Settings.
