### ISSUE TITLE
Hash not matching with this latest update when using mkorthof / chrupd update script

### ISSUE THREAD

**Issue by eglimpse** [macchrome/winchrome#153]

**Comment by macchrome** [comment]
So what!

**Comment by eglimpse** [comment]
It's not concerning to you that the hash in the RSS feed doesn't match the hash of the binary?

**Comment by ltguillaume** [comment]
> It's not concerning to you that the hash in the RSS feed doesn't match the hash of the binary?

Have you tried comparing the hashes yourself? They match.
