### ISSUE TITLE
Malicious code in latest release

### ISSUE THREAD

**Issue by eglimpse** [macchrome/winchrome#154]
C:\Files\Scripts>.\chromiumUpdate.cmd

C:\Files\Scripts>cd /d C:\Files\Scripts

C:\Files\Scripts>.\chrupd.cmd -name Ungoogled-Marmaduke -arch 64bit -channel stable -force -debug 1 -ignHash
DEBUG: $chrInstall="User"
  Simple Chromium Updater
  (chrupd.cmd-19700101)

 OS Detected: "Windows 11" (10.0.22631, Workstation)                                                                    Task Scheduler Mode: Normal "1"                                                                                          Unable to write to logfile, showing output on console only                                                                                                                                                                                      Start (pid:19880 name:powershell scheduler:0 v:19700101 )
 Forcing update, ignoring currently installed Chromium version "130.0.6723.96"

 Using the following settings:
 Source
  "
 github.com
 "
 name
  "
 Ungoogled-Marmaduke
 "
 architecture
  "
 64-bit
 "
 channel
  "
 stable
 "

 Source "github.com" name "Ungoogled-Marmaduke" architecture "64-bit" channel "stable"
 Author from feed: macchrome
 Expected author: macchrome
 Extracted Version: 130.0.6723.96
 Extracted Date: 2024-10-31
 Architecture Match: True
 Download URL: https://github.com/macchrome/winchrome/releases/download/v130.6723.96-M130.0.6723.96-r1356013-Win64/130.0.6723.96_ungoogled_mini_installer.exe
 postparse dataObj.titleMatch = False
 postparse dataObj.editorMatch = True
 postparse dataObj.archMatch = True
 postparse dataObj.channelMatch = True
 postparse dataObj.urlMatch = True
 postparse dataObj.tagMatch = True
 postparse dataObj.hashFormatMatch = True

 New Chromium version "130.0.6723.96" from 2024-10-31 is available (3 days ago)
 Downloading "https://github.com/macchrome/winchrome/releases/download/v130.6723.96-M130.0.6723.96-r1356013-Win64/130.0.6723.96_ungoogled_mini_installer.exe"
 Saving as: "C:\Users\Erik\AppData\Local\Temp\*ungoogled_mini_installer.exe"
 Downloading with curl...
 Curl command: curl.exe -L -o "C:\Users\Erik\AppData\Local\Temp\*ungoogled_mini_installer.exe" "https://github.com/macchrome/winchrome/releases/download/v130.6723.96-M130.0.6723.96-r1356013-Win64/130.0.6723.96_ungoogled_mini_installer.exe"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  109M  100  109M    0     0  24.1M      0  0:00:04  0:00:04 --:--:-- 31.8M
 Download completed with curl
 Hash verification:
   Algorithm: SHA256
   Expected hash:
   Actual hash:   812404F6A57FB57B0C24C65AC23F3CE8DACDA2BF79C1355AEA3E88187F51E404
 Ignoring hash, using calculated value: "812404F6A57FB57B0C24C65AC23F3CE8DACDA2BF79C1355AEA3E88187F51E404"
 SHA256 hash matches "812404F6A57FB57B0C24C65AC23F3CE8DACDA2BF79C1355AEA3E88187F51E404"
 Invoke-VirusTotal id="812404f6a57fb57b0c24c65ac23f3ce8dacda2bf79c1355aea3e88187f51e404" apiUrl="https://www.virustotal.com/api/v3/files/812404f6a57fb57b0c24c65ac23f3ce8dacda2bf79c1355aea3e88187f51e404"
 Invoke-VirusTotal id="812404f6a57fb57b0c24c65ac23f3ce8dacda2bf79c1355aea3e88187f51e404" last_analysis_date="10/31/2024 07:31:18 -05:00" last_analysis_stats="

malicious         : 2
suspicious        : 0
undetected        : 67
harmless          : 0
timeout           : 1
confirmed-timeout : 0
failure           : 0
type-unsupported  : 6

"
 VirusTotal reports downloaded file as: 10/31/2024 07:31:18 -05:00 malicious(2) suspicious(0), exiting...

**Comment by eglimpse** [comment]
https://www.virustotal.com/gui/file/812404f6a57fb57b0c24c65ac23f3ce8dacda2bf79c1355aea3e88187f51e404

**Comment by eglimpse** [comment]
Bkav Pro
W64.AIDetectMalware
Trapmine
Malicious.moderate.ml.score

**Comment by ltguillaume** [comment]
> Bkav Pro W64.AIDetectMalware Trapmine Malicious.moderate.ml.score

Ah yes, the most reliable malware scanners ever /s

**Comment by eglimpse** [comment]
> > Bkav Pro W64.AIDetectMalware Trapmine Malicious.moderate.ml.score
> 
> Ah yes, the most reliable malware scanners ever /s

How reassuring.

**Comment by macchrome** [comment]
Call a wambulance.
