### ISSUE TITLE
Last release version (130.0.6723.96-1) is wrong 

### ISSUE THREAD

**Issue by Feavy** [macchrome/winchrome#155]
Hello,

There is a mismatch between "official" build version and yours. 130.0.6723.96 doesn't exist yet.

[Your build](https://github.com/macchrome/winchrome/releases/tag/v130.6723.96-M130.0.6723.96-r1356013-Win64) : 130.0.6723.96
[Ungoogled-Chromium](https://github.com/ungoogled-software/ungoogled-chromium/tree/708cc83442f8b35b7bc757ad0477927cfb0ff44c) : 130.0.6723.69

Sincerely

**Comment by macchrome** [comment]
Use Ungoogled-Chromium if you are not satisfied.

**Comment by Feavy** [comment]
I thought you project was a build of ungoogled-chromium for windows but I figured out there is ungoogled-chromium-windows! Anyway thanks for the advice, I switched to it 😊
