### ISSUE TITLE
Not an issue per se, but any thoughts of creating avx/avx2 optimized ungoogled versions?

### ISSUE THREAD

**Issue by Black6spdZ** [macchrome/winchrome#156]
best privacy and speed of any browser potentially

**Comment by macchrome** [comment]
Chome/Chromium where necessary will use AVX/AVX2 intrinsics, particularly with graphics. There are also issues with AVX2 builds; such as, thermal throttling. As far as I'm concerned, the marginal gain, and the lack of compatibilty for non AVX/2 users, is not worth the effort.

I do the occaisional AVX/2 build; but am not particularly interested in AVX/2 optimised builds. 

I'm more interested in the Chromium build/compile process: distributed builds.

**Comment by Black6spdZ** [comment]
appreciate the feedback on this. I was under the impression that most "modern" CPUs from a decade or so supported at least the AVX instruction set. I would still like to test your occasional optimized builds.. do you post them here?

**Comment by macchrome** [comment]
https://github.com/macchrome/chromium/releases/tag/v131.6778.142-M131.0.6778.142-r1368529-Win64     - AVX2 build

**Comment by Black6spdZ** [comment]
Web benchmarks on my older HP Ryzen 5 5500U

Version 131.0.6778.142 (Official Build, ungoogled-chromium) (64-bit) AVX2

Speedometer 3.0	15.4            +4.8%
Jetstreem 2.2		213.891      +3.2%
Motionmark 1.3.1	1491.51      +7.3%
BaseMark 3.0		1390.92      +1.6%


Version 131.0.6778.112 (Official Build, ungoogled-chromium) (64-bit)

Speedometer 3.0	14.7
Jetstreem 2.2		207.336
Motionmark 1.3.1	1390.25
BaseMark 3.0		1369.68

I'll test on couple more systems and update tomorrow
