### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by achtchaern** [macchrome/winchrome#157]
Hi, I have noticed and reported some upstream bugs, which I fear will take years to get fixed by the chromium devs. If you're interested: [here](https://issuetracker.google.com/issues/384033046) and [here](https://issuetracker.google.com/issues/383769323)

Anyway, since your builds are running substantially faster than the ungoogled-chromium ones (+ 20 %, tested with Speedometer 2.1), I'd be interested in attempting to compile it myself, so that I can try to fix these bugs (should be doable because I've already located the causing commits - should be revertable). I know it's a steep hill, but as of now I don't think the nessecary info is public, at least in the POV of an almost-noob.

What do you think?

**Comment by macchrome** [comment]
There's not much to think about!

https://github.com/ungoogled-software/ungoogled-chromium/blob/master/docs/building.md
