### ISSUE TITLE
About virus detection

### ISSUE THREAD

**Issue by aojeen** [macchrome/winchrome#17]
When I checked with "virustotal", I got four warnings.
Is it a false positive?
Are there any security issues when using it?

AegisLab
Trojan.Win32.Generic.4!c

Avira (no cloud)
HEUR/AGEN.1025953

F-Secure
Heuristic.HEUR/AGEN.1025953

Qihoo-360
HEUR/QVM202.0.79A5.Malware.Gen

ver.77.0.3865.120 (681094) Installer

**Comment by woolyss** [comment]
Hello @aojeen,
If you download Chromium from here, it is an heurisitic detection of anti-virus.
All is explained at https://chromium.woolyss.com/#malware
