### ISSUE TITLE
Hulu.com

### ISSUE THREAD

**Issue by Aithaks** [macchrome/winchrome#19]
Hello,I can not seem to play anything on chromium while browsing hulu but I can play the same videos on chrome.Could someone please look into it?I get an error whenever I try to play a video,the error is "RUNUNK13", @macchrome

**Comment by woolyss** [comment]
Possibly you are missing widevine support (used for drm video playback). Use this page to test if your browser supports drm - https://bitmovin.com/demos/drm (scroll down to EME, check for a plus next to widevine) [source](https://chromium.woolyss.com/#comment-5069)

**Comment by Aithaks** [comment]
Thanks for the reply and yes it shows it's missing widevine and there is no drm detected.Any ideas on how to fix it? @woolyss

**Comment by woolyss** [comment]
Widevine is a closed source plugin. So we does not share it with Chromium on Windows or Mac. But it is enabled on the **stable** versions (with the GN argument : `enable_widevine = true`)

You can check that at the **chrome://components** page --> "Widevine Content Decryption Module" --> The number must be different than 0.0.0.0 ([My screenshot](https://i.imgur.com/wPLyWa3.png))

Websites to test the Widevine plugin:
- https://bitmovin.com/demos/drm
- https://demo.castlabs.com/ (choose videos with labeled "DRM")
- https://shaka-player-demo.appspot.com/demo/

Note that Chromium developers and most of users do not use this plugin at all. Chromium does not support Widevine natively.
So to use Chromium with Widevine support, you must use a Chromium version with all enabled codecs (standard codecs + MP4/H.264), Widevine support and probably sync.
At [https://chromium.woolyss.com/](https://chromium.woolyss.com/), the first STABLE version is ready for that.

If after that, it still does not work, follow the RobRich instructions at [https://chromium.woolyss.com/?all=1#comment-4955](https://chromium.woolyss.com/?all=1#comment-4955). This is the copy-paste of RobRich (one of our developers) 👍 



> I have not bothered with Widevine in a long time, but IIRC, the WidevineCdm directory should be located in Chrome's userdata directory. Replace *username* with your local Windows account username.

>C:\Users\*username*\AppData\Local\Google\Chrome\User Data

>Copy the WidevineCdm directory and its underlying files to:

>C:\Users\*username*\AppData\Local\Chromium\User Data

>Alternatively, you instead even could set a directory junction or symbolic link.

>----------------

>BTW, I noticed you are using a MD's sync build, which I assume also means it probably includes the version of Widevine available to be built with Chromium as well. If a previous Chromium build's Widevine worked, obtain the older version, extract the WidevineCDM directory, and replace your current WidevineCDM with it.

>----------------

>You might also first try the component updater before doing any of the above, but I am not sure it will update Widevine for a Chromium build. Again, it has been a long time since I have dealt with Widevine issues.

>chrome://components/

>----------------

>BTW, Widevine aside, it probably is a good idea to occasionally run the component updater anyway if one is using Chromium "stable" builds, as various components can be and often area updated between stable releases.


Hope it will help you.
Other way, use Google Chrome ! ;)

Regards

Jerry

**Comment by Aithaks** [comment]
Thank you,it works now @woolyss
