### ISSUE TITLE
Dark Mode Freezes in Ungoogled

### ISSUE THREAD

**Issue by brunoalvieira** [macchrome/winchrome#20]
When you try to enable # enable-force-dark mode, regardless of the option you choose, when you restart your browser, the tabs will stop working when you try to load your content, although the feature might even work partially if it wasn't for this problem.

I have not tested whether this problem also occurs in the normal version.
![Clipboarder 2019 10 27-002](https://user-images.githubusercontent.com/39491972/67643637-48e42580-f8f8-11e9-98a7-57c84a7969d7.png)

**Comment by woolyss** [comment]
hello @brunoalvieira,
I agree with you. I tested on the latest Stable and Ungoogled versions (78.0.3904.70) of Marmaduke. Same result. When chrome://flags/#enable-force-dark is enabled, there are issues like you said above.

Note before all that chrome://flags are **Experiments** . They are experimental options for Chromium and all Chromium-browsers (Google Chrom, Opera, Vivaldi...) . So they can be bugged.
Also, it can be simply and currently a build regression.
