### ISSUE TITLE
Chromium v84.0.4147.89 can't recognize installed extensions anymore

### ISSUE THREAD

**Issue by LazyZhu** [macchrome/winchrome#28]
Tested upgrade from v83.0.4103.116 to v84.0.4147.89 with flag --disable-encryption and --disable-machine-id.
Anyone has the same issue there?

**Comment by macchrome** [comment]
The windows-disable-machine-id.patch was not appl;ied cleanly.  

New release should resolve problem.

Reinstall unpacked extensions, data should still be intact.
