### ISSUE TITLE
Can you pack your Windows build in a compatible format for chrlauncher?

### ISSUE THREAD

**Issue by woolyss** [macchrome/winchrome#3]
Hello Marmaduke,

I am Jerry from chromium.woolyss.com. Hope all is ok for you! ;)

You probably know [chrlauncher](https://github.com/henrypp/chrlauncher). It is a small and very fast portable launcher and updater for Chromium, on Windows, developped by Henry++.

Your [Windows builds](https://github.com/macchrome/winchrome/releases) can not be launched by chrlauncher because the archive content is not standard :/
You packed the ZIP in another 7z format.

Can you simply your archive content to be compatible with chrlauncher?

For help, check the "Archive" builds at https://chromium.woolyss.com/#windows-64-bit Except yours, they are all compatible with chrlauncher.

I also prepared a chrlauncher archive with your last build, for test:
https://chromium.woolyss.com/f/chrlauncher-win64-dev-codecs-nosync-experimental.zip

Regards

**Comment by macchrome** [comment]
OK!

chromium-nosync.zip (chrlauncher formatted)
https://github.com/macchrome/winchrome/releases/download/v72.0.3616.0-r609328-Win64/chromium-nosync.zip
SHA1 CDE46CE4EE3631FF6D9BA68D2DB5DBDA01F94543

**Comment by woolyss** [comment]
Thank you very much man. I updated the site and added a "Portable" version for your Windows build! ;)
