### ISSUE TITLE
Pages rendering problem (Chromium v86.0.4240.75-r800218 - ungoogled 64bit Win7)

### ISSUE THREAD

**Issue by rmsEfx** [macchrome/winchrome#32]
Latest release (Chromium v86.0.4240.75-r800218 - ungoogled ) permanently creates page rendering errors of many servieses such as Youtube, Gmail, Windy.com and so on. Below, is the exampling picture of such error.
![windy](https://user-images.githubusercontent.com/68550733/96338929-730b9600-10bb-11eb-9ff6-de87f76d28ff.png)

**Comment by macchrome** [comment]
At the very least state the GPU that you are using, and if hardware acceleration is being used.

Intel(R) HD Graphics 3000 and Hardware-accelerated video decode enabled: no problem with Youtube or Windy.
