### ISSUE TITLE
Widevine buggy

### ISSUE THREAD

**Issue by c0ldplasma** [macchrome/winchrome#34]
I tried the last 3 releases (86 and 85) on the release page and all have the same problem:
When trying to play spotify it skips like 3-4 songs very fast, then plays the next song for 9 seconds and then stops.
On Amazon Prime Video I get a playback error after a couple of seconds.

I tried to replace the included WidevineCdm with an older version, but same result.
Also cleared all user data but that does not help.

**Comment by macchrome** [comment]
I test Widevine with https://bitmovin.com/demos/drm and https://shaka-player-demo.appspot.com/demo/#build=debug_compiled
