### ISSUE TITLE
Why there is no installer?

### ISSUE THREAD

**Issue by tasty0tomato** [macchrome/winchrome#38]
I found that there is an installer version in [ungoogled-chromium-binaries](https://github.com/tangalbert919/ungoogled-chromium-binaries/releases) so I kind of thinking that an installer version can be also released in this repository.

Because I don't know how hard it is so I am sorry if making a installer version isn't easy at all.

**Comment by tasty0tomato** [comment]
WHY CLOSE?

**Comment by ze0ss** [comment]
@tasty0tomato reopen this pls

**Comment by tasty0tomato** [comment]
> @tasty0tomato reopen this pls

sorry, I cannot reopen it. I do not have the permission.  It was the maintainer that closed this issue.
