### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by ze0ss** [macchrome/winchrome#39]
How to update the browser? The releases are arbitrary, and there is no installer in the 7z file, it just straightaway unpacks, it's a portable version.
I have used the "mini installer" to install the `88.0.4324.190` version, it was automatically installed in `C:\Users\(username)\AppData\Local\Chromium\Application`.

So now that version `89.0.4389.82-1` has been released, how to update to it? Because it's 7z does not have any installer to update it.
I would appreciate if you could assist in this as sooner as possible.

![image](https://user-images.githubusercontent.com/56572179/110272599-95fa0080-7ff0-11eb-8631-2022dedacf0a.png)

**Comment by himanshuchandola-zz** [comment]
Delete all Files that are in your chromium installation folder and paste new files.

**Comment by ze0ss** [comment]
Wtf

**Comment by himanshuchandola-zz** [comment]
> Wtf

Not joking around here that how i update it every time. By removing every files inside this folder:- C:\ProgramData\Ungoogled Chromium

and putting new files from github directly ... 

I guess most of the users do that.

Or us this script to update:- https://github.com/NeverDecaf/ungoogled-updater

This script install macchrome builds.

**Comment by ze0ss** [comment]
@macchrome say something lol
