### ISSUE TITLE
"No sync" build but sync is there

### ISSUE THREAD

**Issue by sluTTYusr** [macchrome/winchrome#4]
What exactly does no-sync mean if the sync component is still there?
I downloaded the No sync build from here: https://github.com/macchrome/winchrome/releases/tag/v72.0.3617.0-r609662-Win64

Yet the sync component is very much active.

**Comment by macchrome** [comment]
The build parameters for the Windows no-sync build include:

google_api_key = "no"
google_default_client_id = "no"
google_default_client_secret = "no"
use_official_google_api_keys = false

The sync component is an integral (and necessary) part of Chrome/Chromium;  I have no interest in trying to remove it.

How to Enable or Disable Sync in Google Chrome in Windows:

https://www.tenforums.com/tutorials/115678-enable-disable-sync-google-chrome-windows.html

**Comment by sluTTYusr** [comment]
Ok, so the tag "No sync" is a little misleading.
I don't see why the sync thing should be necessary if I don't use it. It wasn't necessary in the past at least.
But thanks for the explanation. And the build, of course :)
