### ISSUE TITLE
A few questions about latest version

### ISSUE THREAD

**Issue by Marek33** [macchrome/winchrome#50]
First off, thank you for a new Ungoogled version, but I have a few questions about it.

1. Why is the **headers.sec-ch-ua.name** and **headers.sec-ch-ua-mobile.name** spyware enabled?

2. What's the deal with the weird **Audio formats**?

3. Why the Safe Browser patch wasn't used? And will it be, in the next version?

4. And at the end, will you add the flag, so the browser would clean history after closing?

**Comment by Rusenche** [comment]
First off thank you for a new Ungoogled version.

I also have a question.

When testing https://github.com/Hibbiki/chromium-win32/releases/tag/v92.0.4515.107-r885287 -> https://github.com/Hibbiki/chromium-win32/releases/download/v92.0.4515.107-r885287/chrome.nosync.7z

**the page translation menu has it.**

Here is a photo: http://store.picbg.net/pubpic/FE/0F/8897c60911cefe0f.png

And when testing **ungoogled-chromium**-92.0.4515.107-1_Win32 -> https://github.com/macchrome/winchrome/releases/download/v92.0.4515.107-r885287-Win64/ungoogled-chromium-92.0.4515.107-1_Win32.7z

**page translation menu is missing.**

Here is a picture: http://store.picbg.net/pubpic/85/37/6ff007e769ee8537.png

I use ungoogled-chromium, but it is extremely important for me to have the translation menu available and working.

Please return the translation menu, I tried using chrome://flags, but I don't know which one exactly and I'm not successful. Can you help?!

**Comment by macchrome** [comment]
1. User-Agent Client Hints: --disable-features=UserAgentClientHint - the onus is on the user to set.
2. I'm not familiar with the "weird" Audio format[s].
3. I prefer to disable safe browsing by using code policies - chrome://safe-browsing/
4. --enable-features=ClearDataOnExit - https://github.com/Eloston/ungoogled-chromium/pull/1564 - has been implemented.

https://github.com/Eloston/ungoogled-chromium/blob/master/docs/flags.md

The translate feature is not extremely important for me: figure it out for yourself.
https://github.com/Ahrotahn/ungoogled-chromium/commit/32193142113126a668f845016e07fa616fc8c3f9
https://github.com/Eloston/ungoogled-chromium/pull/1175/commits/32193142113126a668f845016e07fa616fc8c3f9

**Comment by Rusenche** [comment]
> The translate feature is not extremely important for me: figure it out for yourself.
> [Ahrotahn/ungoogled-chromium@3219314](https://github.com/Ahrotahn/ungoogled-chromium/commit/32193142113126a668f845016e07fa616fc8c3f9)
> [Eloston/ungoogled-chromium@3219314](https://github.com/Eloston/ungoogled-chromium/commit/32193142113126a668f845016e07fa616fc8c3f9)

I have absolutely no idea what to do with these hundreds of lines of program code so that the translation menu appears to me. :|

**Comment by Marek33** [comment]
@macchrome

1. Yes, I have that enabled in Iridium as well, but why not have it as a patch? **_Or even better, why not have it as a flag in the chrome:flags?_**

2. The Audio Formats, are different, than most Chromium browsers, so the browser automatically sticks out of the crowd. For reference, check this site, and compare with normal Chromium, Chrome, Brave or even Iridium browser: https://www.amiunique.org/ **_Have you checked that site?_**

3. I see, and can you tell me, how to disable it there? Since the chrome://safe-browsing/ says _**This site can’t be reached**. _**Now, it works as it should.**_

4. Yes, it works, but it seems to delete all bookmarks. I already asked _**Ahrotahn**_ if it can be fixed, so hopefully it can be done.
