### ISSUE TITLE
Any chance for continuous 32-bit releases?

### ISSUE THREAD

**Issue by tomasz1986** [macchrome/winchrome#56]
I know the repository literally has "Chromium for 64-bit Windows" in the name, but would it be a major strain to release both 32-bit and 64-bit versions of Chromium on a regular basis? At the moment, the 32-bit releases seem rather irregular.

The reason for asking is that at this very moment your repository seems to be the one and only source of updated Ungoogled Chromium Windows binaries.

Personally, I need those for my Intel Atom devices that have 32-bit UEFI, and as such cannot run Windows x64.

**Comment by DI555** [comment]
yes, it would be very greatfull !!! we use so much 32bits systems yet !
