### ISSUE TITLE
Is this version fully portable?

### ISSUE THREAD

**Issue by bacon-cheeseburger** [macchrome/winchrome#61]
I wasn't sure where else to ask this so I'm asking here...  Is this Windows 64bit version of ungoogled Chromium fully portable as well? I prefer to just unpack it, point it to my profile dir, and go. No installer, no registry entries, no link with my Windows install in any way. I'm not interested in "portable" apps that just add/remove registry entries on start/exit and things like that.

Thanks for clarifying!

**Comment by ddodogames** [comment]
> I wasn't sure where else to ask this so I'm asking here... Is this Windows 64bit version of ungoogled Chromium fully portable as well? I prefer to just unpack it, point it to my profile dir, and go. No installer, no registry entries, no link with my Windows install in any way. I'm not interested in "portable" apps that just add/remove registry entries on start/exit and things like that.
> 
> Thanks for clarifying!

you can try this instead: https://portapps.io/app/ungoogled-chromium-portable/
