### ISSUE TITLE
It crashes

### ISSUE THREAD

**Issue by Rusenche** [macchrome/winchrome#62]
```
@Anon7302 - 22 Oct 2021, 12:04
ungoogled-chromium-95.0.4638.54-2_Win64.7z - When I clear browser data, it crashes/quits.

The Oct 20 release works fine. What are the differences between the two releases?
```

- > https://chromium.woolyss.com/#comment-7302
- > https://github.com/macchrome/winchrome/releases/tag/v95.0.4638.54-r920003-Win64

**Comment by Rusenche** [comment]
Hardly anyone expected an answer. We all knew that the topic would be closed and moved to the Recycle Bin like any other topic.

Even this crashes https://github.com/macchrome/winchrome/releases/download/v95.0.4638.54-r920003-Win64/ungoogled-chromium-95.0.4638.54-1_Win32.7z .... but is left proud.

**Comment by macchrome** [comment]
... it's left proudly for diagnostic purposes!
