### ISSUE TITLE
Widevine Content Decryption Module not working

### ISSUE THREAD

**Issue by knuxyl** [macchrome/winchrome#65]
Version 96.0.4664.110 (Official Build, ungoogled-chromium) (64-bit)

Amazon Prime Video wouldn't work saying widevine not available, so I checked if widevine was installed.
At first in
chrome://components
it says "Status - New" but version "0.0.0.0"
Clicking check for update causes it to be stuck in "Status - Checking for status..."

**Comment by Tarnum-tst** [comment]
Not working? Pfft... it is simply not included with the installer, only in *.7z package. You could also extract it using 7-Zip from official Chrome installer. Example: https://dl.google.com/release2/chrome/adbwpsxlwmmcfevd3d6gwkcekqlq_96.0.4664.110/96.0.4664.110_chrome_installer.exe

**Comment by knuxyl** [comment]
Oh I didn't know. I usually use the standalone but switched to the installer. Thanks!
