### ISSUE TITLE
Widevine issues?

### ISSUE THREAD

**Issue by anmolbyte** [macchrome/winchrome#69]
It seems that widevine is not working for me- I cannot play spotify and watch DRM encrypted video on [castlabs](https://demo.castlabs.com/#/player/stats?cfg=eyJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly9jb250ZW50LnBsYXllcnMuY2FzdGxhYnMuY29tL2RlbW9zL2RybS1hZ2VudC9tYW5pZmVzdC5tcGQiLCJ0eXBlIjoiYXBwbGljYXRpb24vZGFzaCt4bWwiLCJkcm1Qcm90ZWN0ZWQiOnRydWV9LCJhdXRvcGxheSI6dHJ1ZSwibWFuaWZlc3QiOnt9LCJhYnIiOnsicmVzdHJpY3Rpb25zIjp7fX0sImRybSI6eyJlbnYiOiJEUk10b2RheV9TVEFHSU5HIiwiY3VzdG9tRGF0YSI6eyJtZXJjaGFudCI6ImNsaWVudF9kZXYiLCJ1c2VySWQiOiJwdXJjaGFzZSIsInNlc3Npb25JZCI6ImRlZmF1bHQiLCJhc3NldElkIjoiYWdlbnQtMzI3IiwidmFyaWFudElkIjoiIiwiYXV0aFRva2VuIjoiIn19LCJwcmVmZXJyZWRUZXh0TGFuZ3VhZ2UiOiJlbiIsInJlc3RyaWN0aW9ucyI6e30sIm1ldGFkYXRhIjp7InRpdGxlIjoiTXVsdGktS2V5IERSTSIsInN1YnRpdGxlcyI6ZmFsc2UsImF1ZGlvQ29kZWNzIjpbIkFBQyJdLCJxYSI6ZmFsc2UsImN1c3RvbUhvc3RlciI6IiIsImJ5bGluZSI6IkFnZW50IDMyNzogT3BlcmF0aW9uIEJhcmJlcnNob3A8YnI%2BQmxlbmRlciBGb3VuZGF0aW9uIHwgPGEgaHJlZj1cImh0dHBzOi8vY3JlYXRpdmVjb21tb25zLm9yZy9saWNlbnNlcy9ieS1uZC8yLjAvXCI%2BQ0MtQlktTkQ8L2E%2BIiwidGVzdENhc2VzIjpbXSwibXVsdGlBdWRpbyI6ZmFsc2UsImJyb3dzZXJzIjpbXSwidmlkZW9Db2RlY3MiOlsiaDI2NCJdLCJkZXNjcmlwdGlvbiI6IiIsImhvc3RlciI6IkNhc3RMYWJzIn0sInRleHRzdHlsZSI6eyJmb250RmFtaWx5IjoiJ1JvYm90bycsIHNhbnMtc2VyaWYiLCJmb250Q29sb3IiOiJ3aGl0ZSIsImJhY2tncm91bmRDb2xvciI6InJnYmEoMCwgMCwgMCwgMC43NSkifSwicGx1Z2lucyI6e30sImlkIjoxNTMzfQ%3D%3D&assetId=1533). Is anyone else having this issue?

**Comment by ghost** [comment]
> It seems that widevine is not working for me- I cannot play spotify and watch DRM encrypted video on [castlabs](https://demo.castlabs.com/#/player/stats?cfg=eyJzb3VyY2UiOnsidXJsIjoiaHR0cHM6Ly9jb250ZW50LnBsYXllcnMuY2FzdGxhYnMuY29tL2RlbW9zL2RybS1hZ2VudC9tYW5pZmVzdC5tcGQiLCJ0eXBlIjoiYXBwbGljYXRpb24vZGFzaCt4bWwiLCJkcm1Qcm90ZWN0ZWQiOnRydWV9LCJhdXRvcGxheSI6dHJ1ZSwibWFuaWZlc3QiOnt9LCJhYnIiOnsicmVzdHJpY3Rpb25zIjp7fX0sImRybSI6eyJlbnYiOiJEUk10b2RheV9TVEFHSU5HIiwiY3VzdG9tRGF0YSI6eyJtZXJjaGFudCI6ImNsaWVudF9kZXYiLCJ1c2VySWQiOiJwdXJjaGFzZSIsInNlc3Npb25JZCI6ImRlZmF1bHQiLCJhc3NldElkIjoiYWdlbnQtMzI3IiwidmFyaWFudElkIjoiIiwiYXV0aFRva2VuIjoiIn19LCJwcmVmZXJyZWRUZXh0TGFuZ3VhZ2UiOiJlbiIsInJlc3RyaWN0aW9ucyI6e30sIm1ldGFkYXRhIjp7InRpdGxlIjoiTXVsdGktS2V5IERSTSIsInN1YnRpdGxlcyI6ZmFsc2UsImF1ZGlvQ29kZWNzIjpbIkFBQyJdLCJxYSI6ZmFsc2UsImN1c3RvbUhvc3RlciI6IiIsImJ5bGluZSI6IkFnZW50IDMyNzogT3BlcmF0aW9uIEJhcmJlcnNob3A8YnI%2BQmxlbmRlciBGb3VuZGF0aW9uIHwgPGEgaHJlZj1cImh0dHBzOi8vY3JlYXRpdmVjb21tb25zLm9yZy9saWNlbnNlcy9ieS1uZC8yLjAvXCI%2BQ0MtQlktTkQ8L2E%2BIiwidGVzdENhc2VzIjpbXSwibXVsdGlBdWRpbyI6ZmFsc2UsImJyb3dzZXJzIjpbXSwidmlkZW9Db2RlY3MiOlsiaDI2NCJdLCJkZXNjcmlwdGlvbiI6IiIsImhvc3RlciI6IkNhc3RMYWJzIn0sInRleHRzdHlsZSI6eyJmb250RmFtaWx5IjoiJ1JvYm90bycsIHNhbnMtc2VyaWYiLCJmb250Q29sb3IiOiJ3aGl0ZSIsImJhY2tncm91bmRDb2xvciI6InJnYmEoMCwgMCwgMCwgMC43NSkifSwicGx1Z2lucyI6e30sImlkIjoxNTMzfQ%3D%3D&assetId=1533). Is anyone else having this issue?

Nope. Your url on castlabs is playing well. I've tested on Chromium 98.0.4758.80 (Official Build, ungoogled-chromium) (64 бит)

**Comment by anmolbyte** [comment]
dang. I've tried on multiple computers and I get the same issue. Must be a me thing, somehow.

**Comment by ajarang** [comment]
Just noticed that winget is installing 98.0.4758.102, but it isn't displayed as the latest version on the releases tab. Can you try on the latest version?

**Comment by anmolbyte** [comment]
Was able to fix the problem by manually dragging Widevine CDM as given in [this link](https://chromium.woolyss.com/#widevine) to get it to work. I think the latest release does not have Widevine Installed. It's likely if Widevine is working for you, you updated from a previous build that had widevine installed. 
@macchrome please let me know if this is the case.
