### ISSUE TITLE
Floccus Extension

### ISSUE THREAD

**Issue by mmtech2012** [macchrome/winchrome#71]
Hi
According to https://github.com/floccusaddon/floccus/issues/847
The "Google Drive" part of Floccus Extension isn't work properly and it seems Eloston doesn't care https://github.com/Eloston/ungoogled-chromium/issues/1437
would you fix this please?

**Comment by macchrome** [comment]
https://github.com/macchrome/winchrome/releases/tag/v99.0.4844.51-r961656-Win64 has been compiled without domain substitution, try that.

**Comment by mmtech2012** [comment]
thank you for your time.
I got new error
https://i.imgur.com/21R65Qm.png

**Comment by macchrome** [comment]
Try building  a sync version of ungoogled (supply your own keys) without the respective domain substitution and apply this patch: https://github.com/ungoogled-software/ungoogled-chromium-archlinux/blob/master/use-oauth2-client-switches-as-default.patch

Alternatively, use a standard build of Chrome/Chromium in conjunction with uMatrix and uBlock, associated CLI commands, and pi-hole.

Sync is not particularly compatible with ungoogled: pick and mix the various ungoogled patches and do your own build!
