### ISSUE TITLE
Windows 11 - chrlauncher - error while checking for update 

### ISSUE THREAD

**Issue by MarvinFS** [macchrome/winchrome#73]
People, can't solve the issue with updates.
It just doesn't work always saying "error while checking for update"
Same LAN same internet connection other laptop with Win10 everything updates fine, tried to redownload chrlauncher and setup to new folder - nothing. Tried to change to custom check version URL in ini - nothing. Any ideas or how to troubleshoot? any advanced logging is possible?
Tried playing with internal windows firewall, running as admin, folder permissions, etc... not helping.
 

Windows 11
![2022-03-30_23-15-21](https://user-images.githubusercontent.com/7998636/160903618-ad5fb68a-e60a-4434-a1ac-f104912e6df4.png)

Windows 10 - same network same internet connection
![photo_2022-03-31_00-19-19](https://user-images.githubusercontent.com/7998636/160904182-a2a7a2c9-4caf-4c68-934e-b92236983810.jpg)

Any ideas?

**Comment by MarvinFS** [comment]
Tried to change system wise date/regional settings separator - no luck either...

**Comment by macchrome** [comment]
Contact the author of chrlauncher.
