### ISSUE TITLE
Are patches out of date or am I confused?

### ISSUE THREAD

**Issue by JordanBoulan** [macchrome/winchrome#80]
Are  your patches two years out of date?

Or am I misunderstanding? Are you  using the up to date patches and just those specific ones from two years ago need to be changed for windows? Or maybe you just haven't bothered to update the repo? 

Seems odd that only a few patches from two years ago would need modification and not any others?

**Comment by euclidsss** [comment]
check releases

**Comment by macchrome** [comment]
The most recent patches are always used:

https://github.com/ungoogled-software/ungoogled-chromium
https://github.com/ungoogled-software/ungoogled-chromium-windows/commits/master
