### ISSUE TITLE
Crashesh - Chromium v103.0.5060.53-r1002911 - ungoogled

### ISSUE THREAD

**Issue by Rusenche** [macchrome/winchrome#82]
When installing "crx" v.103.0.5060.53 crashes. Tried with several random "crx".

The other problem is if you add a random unpacked extension and then try to package it in order to create "crx" - you get an error and it is impossible to create "crx".

And let's not forget - all this is provided that chrome://flags/#hide-extensions-menu -> Enabled.

https://github.com/ungoogled-software/ungoogled-chromium/pull/1994#issuecomment-1162603375

**Comment by macchrome** [comment]
Well it's probably best to forget  chrome://flags/#hide-extensions-menu

The concept of  hiding the extensions menu can best be described as specious; needless to say, i will not be including the patch in future builds.
