### ISSUE TITLE
version 108 add affiliate ids and links to your urls automatically

### ISSUE THREAD

**Issue by ezzdev** [macchrome/winchrome#87]
version 108 add affiliate ids and links to your urls automatically

try to enter etsy.com it will be redirected to a url with affiliate link for the author !!!

Can you explain ?!!?!?

**Comment by macchrome** [comment]
Which author are you talking about?

A cursory Google search: https://www.etsy.com/legal/affiliates/

I suggest that you add etsy.com to you HOSTS file and use a plugin such as uBlockO

It's not for me to explain anything to you.
