### ISSUE TITLE
is 109 slower then latest 108?

### ISSUE THREAD

**Issue by uDEV2019** [macchrome/winchrome#88]
Don't know if it is an issue or something we just should talk about...

For me 109 is extremly slow when it comes to loading a website (tested different websites).
Interaction of Extension (e.g. Chromium Web Store) are slow too, when it comes to web requests.

Did a clean install with no extensions and it is slow too.

Anyone else observed this behaviour?

**Comment by macchrome** [comment]
Subjectively, I've not noticed a marked decrease in performance. Perhaps, future changes to the PGO prifle will ameliorate the situation. Try deleting the GrShaderCache and ShaderCache in the profile directory.

**Comment by uDEV2019** [comment]
Like i said, i did a clean install (complete new profile; no extensions, default settings) and there is no change in performance.
Therefor GrShaderCache and ShaderCache couldn't be the problem.
