### ISSUE TITLE
Are these builds faster than the "official" Ungoogled Chromium builds?

### ISSUE THREAD

**Issue by achtchaern** [macchrome/winchrome#89]
Sorry, I guess this is not the right place to ask, but I found no better way.. 

Compared to the [official builds](https://github.com/ungoogled-software/ungoogled-chromium-windows), are your builds faster due to the compiler optimizations?

**Comment by ltguillaume** [comment]
The difference primarily is Widevine I think

**Comment by macchrome** [comment]
The build parameters are as stated in the description: thin lto and pgo.

Do your own comparison.

**Comment by achtchaern** [comment]
Did some testing with BrowserBench.net. According the results, this build runs about 9 percent faster than the official one.

Same exact steps done, cache deleted before the benchmark runs. https://imgur.com/a/0KRjb7P

**Comment by ltGuillaume** [comment]
> Did some testing with BrowserBench.net. According the results, this build runs about 9 percent faster than the official one.
> 
> Same exact steps done, cache deleted before the benchmark runs. https://imgur.com/a/0KRjb7P

Nice. How does it compare to Brave, considering they've got - crypto and homebrew ad stuff aside - some interesting fingerprint mitigations in place that Ungoogled doesn't sport.

**Comment by macchrome** [comment]
That's good to know.
