### ISSUE TITLE
webRTCIPHandlingPolicy

### ISSUE THREAD

**Issue by mp3sova** [macchrome/winchrome#90]
If I understand correctly, you build assemblies with:
--force-webrtc-ip-handling-policy=default_public_interface_only
is it possible to somehow patch chrome.dll to hex to get and not use third-party plugins
--force-webrtc-ip-handling-policy=disable_non_proxied_udp

**Comment by macchrome** [comment]
http://peter.sh/experiments/chromium-command-line-switches/

--force-webrtc-ip-handling-policy is a CLI parameter


Launch chrome.exe with these additional parameters: **--enforce-webrtc-ip-permission-check --force-webrtc-ip-handling-policy=disable_non_proxied_udp**


**Programmatically:**

The policy is set in _**chrome/browser/ui/browser_ui_prefs.cc**_

  registry->RegisterStringPref(prefs::kWebRTCIPHandlingPolicy,
                               blink::kWebRTCIPHandlingDefault);


**DEFINITIONS** _**webrtc_ip_handling_policy.h**_            


#define THIRD_PARTY_BLINK_PUBLIC_COMMON_PEERCONNECTION_WEBRTC_IP_HANDLING_POLICY_H_

#include "third_party/blink/public/common/common_export.h"

namespace blink {

// This is the default behavior of Chrome. Currently, WebRTC has the right to
// enumerate all interfaces and bind them to discover public interfaces.
BLINK_COMMON_EXPORT extern const char kWebRTCIPHandlingDefault[];
					
// WebRTC should only use the default route used by http. This also exposes the
// associated default private address. Default route is the route chosen by the
// OS on a multi-homed endpoint.
BLINK_COMMON_EXPORT extern const char
    kWebRTCIPHandlingDefaultPublicAndPrivateInterfaces[];

// WebRTC should only use the default route used by http. This doesn't expose
// any local addresses.
BLINK_COMMON_EXPORT extern const char
    kWebRTCIPHandlingDefaultPublicInterfaceOnly[];

// WebRTC should only use TCP to contact peers or servers unless the proxy
// server supports UDP. This doesn't expose any local addresses either.
BLINK_COMMON_EXPORT extern const char kWebRTCIPHandlingDisableNonProxiedUdp[];

}  // namespace blink

#endif  // THIRD_PARTY_BLINK_PUBLIC_COMMON_PEERCONNECTION_WEBRTC_IP_HANDLING_POLICY_H_
