### ISSUE TITLE
ungoogled-chromium-109.0.5414.130-1_Win64.7z

### ISSUE THREAD

**Issue by Tarnum-tst** [macchrome/winchrome#91]
Please consider building ungoogled-chromium-109.0.5414.130-1_Win64.7z with Windows 7 SP1 x64 compatibility. Thanks in advance!

**Comment by macchrome** [comment]
NO!

**Comment by andika207** [comment]
> Please consider building ungoogled-chromium-109.0.5414.130-1_Win64.7z with Windows 7 SP1 x64 compatibility. Thanks in advance!

https://github.com/win32ss/supermium
