### ISSUE TITLE
Spotify not working.

### ISSUE THREAD

**Issue by Rexadev** [macchrome/winchrome#94]
## These sites show I use DRM -
1. https://bitmovin.com/demos/drm
2. https://demo.castlabs.com/ (Choose videos with labeled "DRM")
3. https://shaka-player-demo.appspot.com/demo/

## Issue

Songs just skip though.

## System

Windows 10 x64
Browser - https://chromium.woolyss.com/f/chrlauncher-win64-stable-ungoogled.zip

**Comment by macchrome** [comment]
1. Songs are skipping on Spotify (possible explanation) https://github.com/ungoogled-software/ungoogled-chromium/issues/1258#issuecomment-873456050

2. Add to  CLI (no deed to add addtitional flags to ungoogled): "--js-flags=--jitless"  --jitless also implies --no-expose-wasm
