### ISSUE TITLE
"Ad blocking" toggle in settings is not being saved

### ISSUE THREAD

**Issue by achtchaern** [macchrome/winchrome#95]
- Disable the integrated adblocker (chrome://settings/adblock)
- Restart Chromium
- Adblocker is enabled again

**Comment by macchrome** [comment]
Make sure that all the processes associated with Chromium have been terminated.
Run Chromium in a portable manner; clear the cache if necessary.
This is an experimental feature,in mitigation of MV3

I've literally open and shut the browser in all permissible Adblock permutations and the only time there was a problem was there was an associated process still running.

**Comment by achtchaern** [comment]
Your previous comment regarding me not fully closing the browser inbetween is not correct.

https://youtu.be/mNUtfzF0Ef0

**Comment by macchrome** [comment]
Sporadically,  the Adblocker is enabled again, but the builtin subscriptions list is cleared.

I'll invetsigate.

**Comment by macchrome** [comment]
I don't appreciate my name being spread across youtube.

At best it's a trivial problem, which will be sotred: use another browser.

**Comment by achtchaern** [comment]
Sorry, I've removed your nickname from the unlisted video. We're absolutely on the same page regarding it being a trivial problem. I just thought that you as the dev and me as a user have a common interest in your code being as bug-free as possible. I mean it's a completely standard practice to report bugs, as small and irrelevant they might be.

Thanks for having a look!
