### ISSUE TITLE
Netflix Issue

### ISSUE THREAD

**Issue by exful3** [macchrome/winchrome#96]
Ungoogled Chromium, running without extensions. Widevine 4.10.2557.0 is detected under chrome://components
![image](https://user-images.githubusercontent.com/9982507/234206279-5f656b8b-a335-45a3-9050-8c564523f40f.png)

**Comment by macchrome** [comment]
I don't know which version of ungoogled you are using.  Try the latest - ungoogled-chromium-112.0.5615.169.  If that does not work then there is not much that I can do.

Familiarise your self with:

https://github.com/ungoogled-software/ungoogled-chromium/issues/1827

https://github.com/ungoogled-software/ungoogled-chromium/issues/1566#issuecomment-879056903

https://github.com/ungoogled-software/ungoogled-chromium/issues/1258#issuecomment-826350804
