### ISSUE TITLE
Global Media Controls cause browser crash

### ISSUE THREAD

**Issue by PorchettaMan** [macchrome/winchrome#98]
Clicking on the top-right media controls icon causes the browser to crash.
The issue started with the first Chromium 113 update and happens even on a clean install. I can't reproduce the crash on official Ungoogled Chromium releases, it only happens with these builds.

**Comment by manciuszz** [comment]
[**Chromium v113.0.5672.119-r1121455 - ungoogled**](https://github.com/macchrome/winchrome/releases/tag/v113.5672.119-M113.0.5672.119-r1121455-Win64) also gets stuck on discord "RTC Connecting" i.e. no voice chat possible, besides the crash.

[**Chromium v113.0.5672.64-r1121455 - ungoogled**](https://github.com/macchrome/winchrome/releases/tag/v113.5672.63-M113.0.5672.64-r1121455-Win64) has no such issues.

**Comment by macchrome** [comment]
@PorchettaMan 

Global media controls will be disabled in the next build.

For the time being, disable it yourself:

chrome://flags/#global-media-controls-cast-start-stop
chrome://flags/#global-media-controls-modern-ui
chrome://flags/#media-remoting-without-fullscreen

CLI

--disable-features=GlobalMediaControlsCastStartStop,GlobalMediaControlsModernUI

@manciuszz

The firewall is enabled by default: chrome://flags/#enable-firewall - disable it and see what the result is.


Alternatively, use the binaries at: https://ungoogled-software.github.io/ungoogled-chromium-binaries/
