### ISSUE TITLE
Netflix does not work, error M7121-1331 when starting the stream

### ISSUE THREAD

**Issue by Aftergit** [macchrome/winchrome#99]
Netflix does not work, error M7121-1331
![Screenshot 2023-05-25 062247](https://github.com/macchrome/winchrome/assets/88626814/1ab32a73-c9c8-4fa8-995e-c1159c745eb0)

**Comment by achtchaern** [comment]
AFAIK, The Widevine DRM has multiple levels of content protection. They differ in terms of general strictness and encryption. Netflix requires the highest protection level. Unfortunately, only registered companies (Google, Mozilla, Brave) can get the certification required for the highest Widevine level to work in their browser. With Ungoogled Chromium-based browsers, this is not possible, unfortunately.

**Comment by Aftergit** [comment]
Thanks for the feedback about the widevine issue, that is pretty strange as widevine is also used with kodi and the netflix addon and that works without any problems. But its ok i will use kodi or msedge just for netflix.
👍

**Comment by ghost** [comment]
they must have changed the level not too long ago because netflix used to work for me in ungoogled chromium. oh well

**Comment by Aftergit** [comment]
> they must have changed the level not too long ago because netflix used to work for me in ungoogled chromium. oh well

They did, it worked for me before also but Google deprecating as of december 2022, see
https://www.xda-developers.com/google-is-deprecating-widevine-for-chromium/
